"""Write the cross-language test fixture for the payout maths.

The Rust port in rust/src/spin.rs must agree with
generate_synthetic_data.spin_from_uniforms. Because the randomness is an
input rather than something each side generates, "agree" can mean *exactly*
— same inputs, same outputs — instead of the usual "the histograms look
similar", which is all you can assert when two languages use different RNGs.

Emits rust/tests/data/spin_golden.json:

    {
      "games": [ {...11 SlotGame fields...} ],
      "cases": [ {"game_id", "u_bonus", "u_win", "u_shape",
                  "is_win", "is_bonus", "multiplier"} ]
    }

Two kinds of case per game:

  - 64 pseudorandom triples, which cover the ordinary paths
  - boundary triples sitting 1e-12 either side of that game's own
    bonus_frequency and base_win_probability, plus u_shape at 0, near 0 and
    near 1. These are where an off-by-one comparison (< vs <=) or a
    catastrophic-cancellation bug in a quantile would show up, and random
    sampling would essentially never hit them.

Usage:
    python tools/export_golden_vectors.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src"))

from generate_synthetic_data import generate_games, spin_from_uniforms  # noqa: E402

SEED = 20260921
N_RANDOM_CASES = 64


def boundary_uniforms(bonus_freq: float, win_prob: float) -> list[tuple[float, float, float]]:
    """Triples that sit exactly on this game's decision boundaries."""
    eps = 1e-12
    interesting_shape = [0.0, 1e-15, 0.5, 1.0 - 1e-15]
    cases: list[tuple[float, float, float]] = []

    for u_shape in interesting_shape:
        # either side of the bonus test
        cases.append((bonus_freq - eps, 0.5, u_shape))
        cases.append((bonus_freq + eps, 0.5, u_shape))
        # bonus missed, either side of the base-game test
        cases.append((min(bonus_freq + eps, 1.0), win_prob - eps, u_shape))
        cases.append((min(bonus_freq + eps, 1.0), win_prob + eps, u_shape))

    # exact zero and one, which is where a <= vs < mistake bites
    cases.append((0.0, 0.0, 0.0))
    cases.append((1.0, 1.0, 0.0))
    return cases


def build(n_games: int) -> dict:
    rng = np.random.default_rng(SEED)
    games = generate_games(n_games, rng)

    case_rng = np.random.default_rng(SEED + 1)
    cases = []

    for game in games:
        triples = [tuple(case_rng.random(3)) for _ in range(N_RANDOM_CASES)]
        triples += boundary_uniforms(game.bonus_frequency, game.base_win_probability)

        for u_bonus, u_win, u_shape in triples:
            is_win, multiplier, is_bonus = spin_from_uniforms(
                game, float(u_bonus), float(u_win), float(u_shape)
            )
            cases.append({
                "game_id": game.game_id,
                "u_bonus": float(u_bonus),
                "u_win": float(u_win),
                "u_shape": float(u_shape),
                "is_win": bool(is_win),
                "is_bonus": bool(is_bonus),
                # Unrounded on purpose. Rounding to cents is a display concern
                # and Python and Rust break exact .5 ties differently, so money
                # rounding is deliberately kept out of the comparison.
                "multiplier": float(multiplier),
            })

    return {
        "_comment": "Generated by tools/export_golden_vectors.py — do not edit by hand.",
        "seed": SEED,
        "games": [
            {
                "game_id": g.game_id,
                "name": g.name,
                "theme": g.theme,
                "volatility": g.volatility.value,
                "rtp": g.rtp,
                "base_win_probability": g.base_win_probability,
                "bonus_frequency": g.bonus_frequency,
                "max_multiplier": g.max_multiplier,
                "payout_scale": g.payout_scale,
                "min_bet": g.min_bet,
                "max_bet": g.max_bet,
            }
            for g in games
        ],
        "cases": cases,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--n-games", type=int, default=15)
    parser.add_argument("--out", type=Path,
                        default=_ROOT / "rust" / "tests" / "data" / "spin_golden.json")
    args = parser.parse_args()

    fixture = build(args.n_games)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    # repr-precision floats: json.dump uses repr for floats, which round-trips
    # exactly through Python and parses identically in Rust.
    args.out.write_text(json.dumps(fixture, indent=1))

    n_bonus = sum(c["is_bonus"] for c in fixture["cases"])
    n_win = sum(c["is_win"] for c in fixture["cases"])
    print(f"{len(fixture['games'])} games, {len(fixture['cases'])} cases "
          f"({n_win} wins, {n_bonus} bonuses) -> {args.out}")
    print(f"{args.out.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
